import { Spline_Sans } from "next/font/google";
import "./globals.css";

const spline = Spline_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${spline.className} min-h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
